---
- name: Create the directories for {{ service.domain }}
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '{{ service.user }}'
    group: '{{ service.user }}'
    mode: '0755'
  loop:
    - '{{ web_home }}/.config/containers/systemd'
    - '{{ web_home }}/.config/systemd/user'
    - '{{ web_home }}/.local/bin'
    - '{{ web_state }}'

- name: Configure the database of {{ service.domain }}
  ansible.builtin.include_tasks: database.yml
  when: service.database is defined

- name: Configure the apps of {{ service.domain }}
  ansible.builtin.include_tasks: app.yml
  loop: '{{ web_service_apps }}'
  loop_control:
    loop_var: app
    label: '{{ app.domain }}'
